Log ADC values
waterloo-rocketry/payload-2023-software pull request #6
Opened 2023-03-26 04:41 UTC by itslinotlie

Very crude solution but it gets the job done. Adcc and Fvr are mcc_generated_files, but the parts I can explain:
- the adc source clock is fosc with a conversion clock (?) at FOSC/100
  - for the ```on-the-pad-charging``` board, this value had to change to allow adc to provide an accurate reading
- the sensor_id values need to change but I don't know what we want them to be (BATT_VOLT = ?, AUX_CUR = BUS_CURR?)

Testing:
Turned off external power, sensor_mag_2 (aux_cur) turned off but the battery was still powering everything so parsley time message continued
![image](https://user-images.githubusercontent.com/56371758/227755459-04d0dc10-c450-4168-be4c-0df61f73ae42.png)

sensor_mag_1 (batt_volt) started at 4095 mV and by the time the testing finished (~5min), it dropped to 3756 mV, not sure if this is normal behaviour or requires further testing?

2023-03-29 11:09 UTC, Joe-Joe-Joe-Joe requested changes
In general, commit names should be descriptive (yes, I am sometimes guilty of the same thing). Saying something like "Read current amps from ADC" tells me exactly what functionality has been added when I go digging through the commit history for whatever reason.

Regardless, I'm very pleased and I appreciate your helping out.

2023-03-29 11:09 UTC, Joe-Joe-Joe-Joe commented on grandpapa_board.X/main.c
> +    uint16_t batt_cur = ADCC_GetSingleConversion(channel_BATT_CURR)/2;
Magic numbers should not be living in the code like this. When I read this code, I know that you're dividing by 2 based on component values on the board, but anyone else probably doesn't. Consider putting this into a macro (`#define CURR_AMP_FACTOR 0.5`) and perhaps a comment indicating where the value comes from

2023-03-29 11:09 UTC, Joe-Joe-Joe-Joe commented on grandpapa_board.X/spi_shit.c
> +    //  these don't belong here but i need to define somewhere
I agree, these do not belong here

2023-04-07 22:47 UTC, closed without merging

2023-04-07 22:48 UTC, itslinotlie commented
Closed because someone else is going to be implementing these changes